version: '3'

services:
  fastapi_app:
    container_name: django_rest_test
    depends_on:
      mysql_server:
        condition: service_healthy
    build: .
    ports:
      - "5000:80"
    volumes:
      - ./django_app:/app

  mysql_server:
    container_name: django_rest_test_db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "django_rest_test"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: