# Generated by Django 5.0.2 on 2024-02-09 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_name', models.TextField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.TextField()),
                ('departure_time', models.TextField()),
                ('fare', models.IntegerField()),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_app.station')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_app.train')),
            ],
        ),
    ]
