# Generated by Django 5.0.2 on 2024-02-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('area', models.TextField()),
                ('genre', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
