# Generated by Django 5.0.2 on 2024-02-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_after', models.TimeField()),
                ('station_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_from', to='station_app.station')),
                ('station_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_to', to='station_app.station')),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.user')),
            ],
        ),
    ]
